// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuletanBublee.Models;

#nullable disable

namespace RuletanBublee.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902205452_AddIndiceVisual")]
    partial class AddIndiceVisual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("RuletanBublee.Models.GiroResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Entregado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndiceVisual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Premio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GirosResultados");
                });
#pragma warning restore 612, 618
        }
    }
}
